export const doctordata = [{ name: 'Puneeth', val: 0 }, { name: 'Kumar', val: 0 }, { name: 'BCF', val: 0 }, { name: 'BCfrostine', val: 0 }]
export const chemist = ['--Select--', 'chemist 1', 'chemist 2', 'chemist 3', 'chemist 4', 'chemist 5']
export const hospital = ['--Select--', 'hospital 1', 'hospital 2', 'hospital 3', 'hospital 4', 'hospital 5']
export const stockiest = ['--Select--', 'stockiest 1', 'stockiest 2', 'stockiest 3', 'stockiest 4', 'stockiest 5']
export const type = ['--Select', 'chemist', 'hospital', 'stockiest']